development:
  access_key_id: AKIAJHAN3EBVVY6W7MVA
  secret_access_key: 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
  # The name of the Amazon S3 bucket where raw videos you be uploaded
  aws_s3_input_video_bucket: input.firehoze.com
  aws_s3_output_video_bucket: output.firehoze.com
  aws_s3_thumbs_bucket: thumbs.firehoze.com
  
test:
  access_key_id: xyz
  secret_access_key: 123
  # The name of the Amazon S3 bucket where raw videos you be uploaded
  aws_s3_input_video_bucket: xyz
  aws_s3_output_video_bucket: abc
  aws_s3_thumbs_bucket: 123
  
production:
  access_key_id: AKIAJHAN3EBVVY6W7MVA
  secret_access_key: 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
  # The name of the Amazon S3 bucket where raw videos you be uploaded
  aws_s3_input_video_bucket: input.firehoze.com
  aws_s3_output_video_bucket: output.firehoze.com
  aws_s3_thumbs_bucket: thumbs.firehoze.com